on: [push, pull_request]
name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    strategy:
      matrix:
        go-version: [1.24.x,1.25.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 23

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: pnpm install
      run: cd ./ethtest/testchain && pnpm install

    - name: Boot test-chain
      run: make start-testchain &

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: |
        make test

