on: [push, pull_request]
name: Test
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    strategy:
      matrix:
        go-version: [1.22.x,1.23.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Yarn install
      run: cd ./ethtest/testchain && yarn install --network-concurrency 1

    - name: Boot test-chain
      run: make start-testchain &

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: |
        make test

  ## NOTE: currently disabled running reorgme tests on gh-actions
  ## but certainly recommend to run them locally!
  #
  # test-with-reorgme:
  #   env:
  #     GOPATH: ${{ github.workspace }}
  #     GO111MODULE: on

  #   defaults:
  #     run:
  #       working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

  #   strategy:
  #     matrix:
  #       go-version: [1.16.x]
  #       os: [ubuntu-latest]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ${{ matrix.go-version }}
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #     with:
  #       path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
  #   - name: Install node
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: '14.x'
  #   - uses: actions/cache@master
  #     id: yarn-cache
  #     with:
  #       path: |
  #         ./tools/testchain/node_modules
  #       key: ${{ runner.os }}-install-reorgme-${{ hashFiles('./tools/testchain/package.json', './tools/testchain/yarn.lock') }}
  #   - name: Yarn install
  #     run: cd ./tools/testchain && yarn install --network-concurrency 1
  #   - name: Start testchain
  #     run: make start-testchain-detached
  #   - name: testchain logs
  #     run: make testchain-logs &> /tmp/chain.log &
  #   - name: Test
  #     timeout-minutes: 20
  #     run: |
  #       make test-with-reorgme
  #   - name: 'Upload chain logs'
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: testchain-logs
  #       path: /tmp/chain.log
  #       retention-days: 5
