on: [push, pull_request]
name: Test
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Test
      run: |
        make test

  ## NOTE: currently disabled running reorgme tests on gh-actions
  ## but certainly recommend to run them locally!
  #
  # test-with-reorgme:
  #   env:
  #     GOPATH: ${{ github.workspace }}
  #     GO111MODULE: on

  #   defaults:
  #     run:
  #       working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

  #   strategy:
  #     matrix:
  #       go-version: [1.16.x]
  #       os: [ubuntu-latest]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ${{ matrix.go-version }}
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #     with:
  #       path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
  #   - name: Install node
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: '14.x'
  #   - uses: actions/cache@master
  #     id: yarn-cache
  #     with:
  #       path: |
  #         ./tools/test-chain/node_modules
  #       key: ${{ runner.os }}-install-reorgme-${{ hashFiles('./tools/test-chain/package.json', './tools/test-chain/yarn.lock') }}
  #   - name: Yarn install
  #     run: cd ./tools/test-chain && yarn install --network-concurrency 1
  #   - name: Start test-chain
  #     run: make start-test-chain-detached
  #   - name: Test-chain logs
  #     run: make test-chain-logs &> /tmp/chain.log &
  #   - name: Test
  #     timeout-minutes: 20
  #     run: |
  #       make test-with-reorgme
  #   - name: 'Upload chain logs'
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: test-chain-logs
  #       path: /tmp/chain.log
  #       retention-days: 5
